language: php
dist: xenial
php:
  - 7.2
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo
services:
  - mysql
before_install:
  - composer install

script:
  # Check code standards
  - >
    vendor/bin/phpcs -n
    --standard=vendor/backdrop/coder/coder_sniffer/Backdrop
    --ignore="vendor/*,i18n_block/*,i18n_forum/*,i18n_select/*,i18n_user/*,i18n_variable/*,i18n_field/i18n_field.inc,i18n_menu/i18n_menu.inc,i18n_object.inc,i18n_path/i18n_path.inc,i18n_string/i18n_string.inc,i18n_taxonomy/i18n_taxonomy.inc,i18n_translation/i18n_translation.inc"
    --extensions=install,module,php,inc,theme .

  # Unit tests

