language: php
dist: xenial
php:
  - 7.2
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo
services:
  - mysql
addons:
  - mariadb: '10.0'
before_install:
  - composer install

script:
  # Check code standards
  - >
    vendor/bin/phpcs -n
      --standard=vendor/backdrop/coder/coder_sniffer/Backdrop
      --ignore="vendor/*,README.md,i18n_block/*,i18n_forum/*,i18n_select/*,i18n_user/*,i18n_variable/*"
      --extensions=install,module,php,inc,theme .

  # Unit tests

