<?php

/**
 * @file
 * Installation file for Internationalization (i18n) module.
 */

/**
 * Implements hook_uninstall().
 */
function i18n_node_uninstall() {
  config_clear('i18n.settings', 'i18n_node');
}

/**
 * Implements hook_update_dependencies().
 */
function i18n_node_update_dependencies() {
  $dependencies['i18n_node'][7000] = array(
    'i18n_string' => 7001,
  );
  return $dependencies;
}
