<?php

/**
 * @file
 * Installation file for Internationalization (i18n) module.
 */

/**
 * Implements hook_uninstall().
 */
function i18n_node_uninstall() {
  config_clear('i18n.settings', 'i18n_node');
}

/**
 * Remove obsolete translation link display setting.
 */
function i18n_node_update_1000() {
  $config = config('i18n.settings');
  if (isset($config->get('i18n_node.hide_translation_links')) {
    $config->clear('i18n_node.hide_translation_links');
    $config->save();
  }
}
