<?php

/**
 * @file
 * Internationalization (i18n) submodule: Multilingual contact forms.
 *
 * @author Jose A. Reyero, 2005
 */

/**
 * Implements hook_menu().
 *
 * Add translate tab to contact config.
 */
function i18n_contact_menu() {
  $items['admin/structure/contact/configure/%contact/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_contact_form_contact_category_delete_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'i18n_contact_form_contact_category_delete_form_submit';
}

/**
 * Remove strings for deleted categories.
 */
function i18n_contact_form_contact_category_delete_form_submit(&$form, $form_state) {
  i18n_string_object_remove('contact_category', $form['contact']['#value']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_contact_form_contact_category_edit_form_alter(&$form, &$form_state) {
  $form['actions']['translate'] = array(
    '#type' => 'submit',
    '#name'   => 'save_translate',
    '#value' => t('Save and translate'),
    '#weight' => 1,
  );
  $form['actions']['cancel']['#weight'] = 2;
  $form['#submit'][] = 'i18n_contact_form_contact_category_edit_form_submit';
}

/**
 * Remove strings for edited/added categories.
 */
function i18n_contact_form_contact_category_edit_form_submit($form, &$form_state) {
  $contact = $form_state['values'];
  i18n_string_object_update('contact_category', $contact);
  if ($form_state['triggering_element']['#name'] == 'save_translate') {
    $cid = $contact['cid'];
    if (!isset($cid)) {
      // New category, get next id.
      $existing = config_get('contact.categories', 'categories');
      $cid = 0;
      foreach ($existing as $key => $values) {
        if ($values['cid'] > $cid) {
          $cid = $values['cid'];
        }
      }
    }
    $form_state['redirect'] = "admin/structure/contact/configure/$cid/translate";
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_contact_form_contact_site_form_alter(&$form, &$form_state) {
  // Example of array translation. The placeholder '*' indicates the name part
  // to be replace by the array keys.
  if (isset($form['cid']['#options'])) {
    $form['cid']['#options'] = i18n_string_translate("contact:category:*:category", $form['cid']['#options'], array('sanitize' => FALSE));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_contact_form_contact_category_list_alter(&$form, &$form_state) {
  foreach ($form['categories'] as $cid => $category) {
    if (is_array($category) && isset($category['operations'])) {
      $form['categories'][$cid]['operations']['#links']['translate'] = array(
        'title' => t('Translate'),
        'href' => "admin/structure/contact/configure/$cid/translate",
      );
    }
  }
}

/**
 * Implements hook_mail_alter().
 */
function i18n_contact_mail_alter(&$message) {
  $message_ids = array(
    'contact_page_mail',
    'contact_page_copy',
    'contact_page_autoreply',
  );
  if (in_array($message['id'], $message_ids)) {
    // Alter the first part of the subject of emails going out if they need
    // translation.
    $contact = i18n_string_object_translate('contact_category', $message['params']['category'], array('langcode' => $message['language']->langcode));
    $message['subject'] = t(
      '[!category] !subject',
      array('!category' => $contact['category'], '!subject' => $message['params']['subject']),
      array('langcode' => $message['language']->langcode)
    );

    if ($message['id'] == 'contact_page_autoreply') {
      // Overwrite the whole message body.
      // Maybe this is not entirely responsible
      // (it might overwrite other existing items altered in by others),
      // but unfortunately Backdrop core cotact module does not make its item
      // identifiable easily.
      $message['body'] = array($contact['reply']);
    }
  }
}
