<?php
/**
 * @file
 * Installation hooks for Internationalization Select (i18n_select) module.
 */

/**
 * Add missing config item if necessary.
 */
function i18n_select_update_1000() {
  $config = config('i18n_select.settings');
  if ($config->get('i18n_select_taxonomy') == NULL) {
    // We stick with "off", so behavior doesn't change on sites.
    $config->set('i18n_select_taxonomy', 0);
    $config->save();
  }
}
