<?php
// $Id$

/**
 * @file
 * Installation file for i18nmenu module.
 */

/**
 * Implements hook_install()
 */
function i18n_menu_install() {
  module_load_install('i18n');
  i18n_install_create_fields('menu_links', array('language'));  
}


/**
 * Implements hook_schema_alter()
 */
function i18n_menu_schema_alter(&$schema) {
  $schema['menu_links']['fields']['language'] = array('type' => 'varchar', 'length' => 12, 'not null' => TRUE, 'default' => '');
}