name: Coding Standards
on: [pull_request]
jobs:
  phpcs:
    name: Run phpcs
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP with CodeSniffer tool
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs:3.7

      # The checkout action refuses to put it outside, so we have to do it in
      # two steps.
      - name: Checkout coding standard
        uses: actions/checkout@v2
        with:
          repository: backdrop-ops/phpcs
          ref: 1.0.0-beta1
          path: phpcs
      - name: Move standard outside current dir
        run: mv phpcs ..

      - uses: actions/checkout@v2

      - name: Backdrop coding standards
        run: phpcs --standard=../phpcs/Backdrop -n *
